<?php

$modulesPath    = dirname(__FILE__) .'/modules/';
$guiPath        = dirname(__FILE__) .'/gui/';
$libPath        = dirname(__FILE__) .'/lib/';
$businessPath   = dirname(__FILE__) .'/business/';
$sqlLayerPath   = dirname(__FILE__) .'/sqllayer/';

$AUTOLOAD_CLASSES = array(
    /* General */
    'ProjectModule'                   => $modulesPath . 'ProjectModule.php',
    'AdminAuth'                       => $libPath . 'Auth.php',
    'FakeAuth'                        => $libPath . 'Auth.php',
    'GuiProjectMenu'                  => $guiPath . 'Menu.php',
    'GuiGridCellID'                   => $guiPath . 'BasicGrid.php',
    'GuiGridValidFor'                 => $guiPath . 'BasicGrid.php',
    'GridColumnFilter_customTag'      => $guiPath . 'BasicGrid.php',
    'GridColumnFilter_customUser'     => $guiPath . 'BasicGrid.php',
    'GridColumnFilter_calendar'       => $guiPath . 'BasicGrid.php',
    'GuiHome'                         => $guiPath . 'Home.php',
    'HomeValidator'                   => $guiPath . 'HomeValidator.php',
    'GuiUserInfo'                     => $guiPath . 'UserInfo.php',
    
    /* In page */
    'InPageModule'                    => $modulesPath . 'inpage/Module.php',
    'InPageAuth'                      => $libPath . 'Auth.php',
    'InPageValidator'                 => $guiPath . 'inpage/Validator.php',
    'GuiInPageMain'                   => $guiPath . 'inpage/Main.php',
    'GuiInPageEvent'                  => $guiPath . 'inpage/Event.php',
    'GuiInPageResource'               => $guiPath . 'inpage/Resource.php',
    'GuiInPageReservationList'        => $guiPath . 'inpage/ReservationList.php',
    'GuiInPageReservation'            => $guiPath . 'inpage/Reservation.php',
    'InPageRegistrationValidator'     => $guiPath . 'inpage/RegistrationValidator.php',
    'GuiInPageRegistration'           => $guiPath . 'inpage/Registration.php',
    'InPageLoginValidator'            => $guiPath . 'inpage/LoginValidator.php',
    
    'GuiCzechTourismMain'             => $guiPath . 'inpage/CzechTourism.php',
    'CzechTourismValidator'           => $guiPath . 'inpage/CzechTourismValidator.php',
    
    /* XML server */
    'XMLAction'                       => $modulesPath . 'xml/Action.php',
    'XMLActionTag'                    => $modulesPath . 'xml/Tag.php',
    'XMLActionSearch'                 => $modulesPath . 'xml/Search.php',
    'XMLActionDetail'                 => $modulesPath . 'xml/Detail.php',
    
    /* AJAX */
    'AjaxAction'                            => $modulesPath . 'ajax/Action.php',
    'AjaxGetVersion'                        => $modulesPath . 'ajax/GetVersion.php',
    'AjaxGetTag'                            => $modulesPath . 'ajax/GetTag.php',
    'AjaxGetCenter'                         => $modulesPath . 'ajax/GetCenter.php',
    'AjaxGetAvailabilityProfile'            => $modulesPath . 'ajax/GetAvailabilityProfile.php',
    'AjaxGetAvailabilityExceptionProfile'   => $modulesPath . 'ajax/GetAvailabilityExceptionProfile.php',
    'AjaxGetUnitProfile'                    => $modulesPath . 'ajax/GetUnitProfile.php',
    'AjaxGetPriceList'                      => $modulesPath . 'ajax/GetPriceList.php',
    'AjaxGetOrganiser'                      => $modulesPath . 'ajax/GetOrganiser.php',
    'AjaxGetCoworker'                       => $modulesPath . 'ajax/GetCoworker.php',
    'AjaxGetUser'                           => $modulesPath . 'ajax/GetUser.php',
    'AjaxSaveUser'                          => $modulesPath . 'ajax/SaveUser.php',
    'AjaxConfirmUser'                       => $modulesPath . 'ajax/ConfirmUser.php',
    'AjaxGetUserDetail'                     => $modulesPath . 'ajax/GetUserDetail.php',
    'AjaxGetUserSubaccount'                 => $modulesPath . 'ajax/GetUserSubaccount.php',
    'AjaxGetUserCreditHistory'              => $modulesPath . 'ajax/GetUserCreditHistory.php',
    'AjaxGetUserPrepaymentInvoice'          => $modulesPath . 'ajax/GetUserPrepaymentInvoice.php',
    'AjaxValidateSession'                   => $modulesPath . 'ajax/ValidateSession.php',
    'AjaxSaveTextStorage'                   => $modulesPath . 'ajax/SaveTextStorage.php',
    'AjaxLoginUser'                         => $modulesPath . 'ajax/LoginUser.php',
    'AjaxRegistrateUser'                    => $modulesPath . 'ajax/RegistrateUser.php',
    'AjaxChangePassword'                    => $modulesPath . 'ajax/ChangePassword.php',
    'AjaxSendPassword'                      => $modulesPath . 'ajax/SendPassword.php',
    'AjaxSendRegistrationEmail'             => $modulesPath . 'ajax/SendRegistrationEmail.php',
    'AjaxGetAttribute'                      => $modulesPath . 'ajax/GetAttribute.php',
    'AjaxGetAttributeCategory'              => $modulesPath . 'ajax/GetAttributeCategory.php',
    'AjaxGetResourcePool'                   => $modulesPath . 'ajax/GetResourcePool.php',
    'AjaxGetResource'                       => $modulesPath . 'ajax/GetResource.php',
    'AjaxGetResourceCalendar'               => $modulesPath . 'ajax/GetResourceCalendar.php',
    'AjaxGetResourcePrice'                  => $modulesPath . 'ajax/GetResourcePrice.php',
    'AjaxGetResourcePoolResource'           => $modulesPath . 'ajax/GetResourcePoolResource.php',
    'AjaxGetReservationCondition'           => $modulesPath . 'ajax/GetReservationCondition.php',
    'AjaxGetNotificationTemplate'           => $modulesPath . 'ajax/GetNotificationTemplate.php',
    'AjaxGetAccountType'                    => $modulesPath . 'ajax/GetAccountType.php',
    'AjaxGetVoucher'                        => $modulesPath . 'ajax/GetVoucher.php',
    'AjaxGetReservation'                    => $modulesPath . 'ajax/GetReservation.php',
    'AjaxSaveReservation'                   => $modulesPath . 'ajax/SaveReservation.php',
    'AjaxSaveReservationVoucher'            => $modulesPath . 'ajax/SaveReservationVoucher.php',
    'AjaxSaveSubstitute'                    => $modulesPath . 'ajax/SaveSubstitute.php',
    'AjaxSwapSubstitute'                    => $modulesPath . 'ajax/SwapSubstitute.php',
    'AjaxCancelReservation'                 => $modulesPath . 'ajax/CancelReservation.php',
    'AjaxCancelReservationEventPackItem'    => $modulesPath . 'ajax/CancelReservationEventPackItem.php',
    'AjaxFailReservationEventPackItem'      => $modulesPath . 'ajax/FailReservationEventPackItem.php',
    'AjaxCancelSubstitute'                  => $modulesPath . 'ajax/CancelSubstitute.php',
    'AjaxPayReservation'                    => $modulesPath . 'ajax/PayReservation.php',
    'AjaxGetEventCalendar'                  => $modulesPath . 'ajax/GetEventCalendar.php',
    'AjaxGetEvent'                          => $modulesPath . 'ajax/GetEvent.php',
    'AjaxDeleteSubaccount'                  => $modulesPath . 'ajax/DeleteSubaccount.php',
    'AjaxSaveSubaccount'                    => $modulesPath . 'ajax/SaveSubaccount.php',
    
    'AjaxGuiAction'                         => $modulesPath . 'ajax/GuiAction.php',
    'AjaxGuiAction2'                        => $modulesPath . 'ajax/GuiAction.php',
    'AjaxGuiCore'                           => $modulesPath . 'ajax/GuiCore.php',
    'AjaxGuiRegistration'                   => $modulesPath . 'ajax/GuiRegistration.php',
    'AjaxGuiProfile'                        => $modulesPath . 'ajax/GuiProfile.php',
    'AjaxGuiProfileDetail'                  => $modulesPath . 'ajax/GuiProfileDetail.php',
    'AjaxGuiProfileCredit'                  => $modulesPath . 'ajax/GuiProfileCredit.php',
    'AjaxGuiSubaccountList'                 => $modulesPath . 'ajax/GuiSubaccountList.php',
    'AjaxGuiSubaccountDetail'               => $modulesPath . 'ajax/GuiSubaccountDetail.php',
    'AjaxGuiDocumentList'                   => $modulesPath . 'ajax/GuiDocumentList.php',
    'AjaxGuiLogin'                          => $modulesPath . 'ajax/GuiLogin.php',
    'AjaxGuiPassword'                       => $modulesPath . 'ajax/GuiPassword.php',
    'AjaxGuiEventList'                      => $modulesPath . 'ajax/GuiEventList.php',
    'AjaxGuiEventWeekList'                  => $modulesPath . 'ajax/GuiEventWeekList.php',
    'AjaxGuiEventDetail'                    => $modulesPath . 'ajax/GuiEventDetail.php',
    'AjaxGuiEventOrganiserDetail'           => $modulesPath . 'ajax/GuiEventOrganiserDetail.php',
    'AjaxGuiResourceList'                   => $modulesPath . 'ajax/GuiResourceList.php',
    'AjaxGuiResourceCalendar'               => $modulesPath . 'ajax/GuiResourceCalendar.php',
    'AjaxGuiResourceAvailability'           => $modulesPath . 'ajax/GuiResourceAvailability.php',
    'AjaxGuiResourcePoolAvailability'       => $modulesPath . 'ajax/GuiResourcePoolAvailability.php',
    'AjaxGuiEventCalendar'                  => $modulesPath . 'ajax/GuiEventCalendar.php',
    'AjaxGuiResourceDetail'                 => $modulesPath . 'ajax/GuiResourceDetail.php',
    'AjaxGuiReservationAttribute'           => $modulesPath . 'ajax/GuiReservationAttribute.php',
    'AjaxGuiReservationList'                => $modulesPath . 'ajax/GuiReservationList.php',
    'AjaxGuiReservationDetail'              => $modulesPath . 'ajax/GuiReservationDetail.php',
    'AjaxGuiSubstituteDetail'               => $modulesPath . 'ajax/GuiSubstituteDetail.php',
    'AjaxGuiSubstituteMandatoryList'        => $modulesPath . 'ajax/GuiSubstituteMandatoryList.php',
    
    /* Settings */
    'GuiSettingsMenu'                 => $guiPath . 'settings/Menu.php',
    'GuiSettingsGeneral'              => $guiPath . 'settings/General.php',
    'SettingsValidator'               => $guiPath . 'settings/GeneralValidator.php',
    
    'BFile'                           => $businessPath . 'BFile.php',
    'OFile'                           => $sqlLayerPath . 'settings/OFile.php',
    'SFile'                           => $sqlLayerPath . 'settings/SFile.php',
    'SLanguage'                       => $sqlLayerPath . 'settings/SLanguage.php',
    'SState'                          => $sqlLayerPath . 'settings/SState.php',
    'BOnlinePayment'                  => $businessPath . 'BOnlinePayment.php',
    'OOnlinePayment'                  => $sqlLayerPath . 'settings/OOnlinePayment.php',
    'SOnlinePayment'                  => $sqlLayerPath . 'settings/SOnlinePayment.php',
    'GridSettingsOnlinePayment'       => $guiPath . 'user/OnlinePaymentList.php',
    'GuiListOnlinePayment'            => $guiPath . 'user/OnlinePaymentList.php',

    'SPortal'                         => $sqlLayerPath . 'settings/SPortal.php',
    'GridSettingsPortal'              => $guiPath . 'settings/PortalList.php',
    
    'BAvailabilityProfile'            => $businessPath . 'BAvailabilityProfile.php',
    'OAvailabilityProfile'            => $sqlLayerPath . 'settings/OAvailProfile.php',
    'SAvailabilityProfile'            => $sqlLayerPath . 'settings/SAvailProfile.php',
    'OAvailabilityProfileItem'        => $sqlLayerPath . 'settings/OAvailProfileItem.php',
    'SAvailabilityProfileItem'        => $sqlLayerPath . 'settings/SAvailProfileItem.php',
    'GuiEditAvailProfile'             => $guiPath . 'settings/AvailProfileEdit.php',
    'AvailProfileValidator'           => $guiPath . 'settings/AvailProfileValidator.php',
    'GridSettingsAvailProfile'        => $guiPath . 'settings/AvailProfileList.php',
    'GuiListAvailProfile'             => $guiPath . 'settings/AvailProfileList.php',
    
    'BAvailabilityExceptionProfile'         => $businessPath . 'BAvailabilityExceptionProfile.php',
    'OAvailabilityExceptionProfile'         => $sqlLayerPath . 'settings/OAvailExProfile.php',
    'SAvailabilityExceptionProfile'         => $sqlLayerPath . 'settings/SAvailExProfile.php',
    'OAvailabilityExceptionProfileItem'     => $sqlLayerPath . 'settings/OAvailExProfileItem.php',
    'SAvailabilityExceptionProfileItem'     => $sqlLayerPath . 'settings/SAvailExProfileItem.php',
    'GuiEditAvailExProfile'                 => $guiPath . 'settings/AvailExProfileEdit.php',
    'AvailExProfileValidator'               => $guiPath . 'settings/AvailExProfileValidator.php',
    'GridSettingsAvailExProfile'            => $guiPath . 'settings/AvailExProfileList.php',
    'GuiListAvailExProfile'                 => $guiPath . 'settings/AvailExProfileList.php',
    
    'BUnitProfile'                    => $businessPath . 'BUnitProfile.php',
    'OUnitProfile'                    => $sqlLayerPath . 'settings/OUnitProfile.php',
    'SUnitProfile'                    => $sqlLayerPath . 'settings/SUnitProfile.php',
    'GuiEditUnitProfile'              => $guiPath . 'settings/UnitProfileEdit.php',
    'UnitProfileValidator'            => $guiPath . 'settings/UnitProfileValidator.php',
    'GridSettingsUnitProfile'         => $guiPath . 'settings/UnitProfileList.php',
    'GuiListUnitProfile'              => $guiPath . 'settings/UnitProfileList.php',
    
    'BTag'                            => $businessPath . 'BTag.php',
    'OTag'                            => $sqlLayerPath . 'settings/OTag.php',
    'OTagPortal'                      => $sqlLayerPath . 'settings/OTagPortal.php',
    'OTagProvider'                    => $sqlLayerPath . 'settings/OTagProvider.php',
    'STag'                            => $sqlLayerPath . 'settings/STag.php',
    'STagPortal'                      => $sqlLayerPath . 'settings/STagPortal.php',
    'STagProvider'                    => $sqlLayerPath . 'settings/STagProvider.php',
    'GuiEditTag'                      => $guiPath . 'settings/TagEdit.php',
    'TagValidator'                    => $guiPath . 'settings/TagValidator.php',
    'GridSettingsTag'                 => $guiPath . 'settings/TagList.php',
    'GuiListTag'                      => $guiPath . 'settings/TagList.php',
    
    'BPriceList'                      => $businessPath . 'BPriceList.php',
    'OPriceList'                      => $sqlLayerPath . 'settings/OPriceList.php',
    'SPriceList'                      => $sqlLayerPath . 'settings/SPriceList.php',
    'OSeason'                         => $sqlLayerPath . 'settings/OSeason.php',
    'SSeason'                         => $sqlLayerPath . 'settings/SSeason.php',
    'GuiEditPriceList'                => $guiPath . 'settings/PriceListEdit.php',
    'PriceListValidator'              => $guiPath . 'settings/PriceListValidator.php',
    'GridSettingsPriceList'           => $guiPath . 'settings/PriceList.php',
    'GuiListPriceList'                => $guiPath . 'settings/PriceList.php',
    
    'BProviderAccountType'            => $businessPath . 'BProviderAccountType.php',
    'OProviderAccountType'            => $sqlLayerPath . 'settings/OProviderAccountType.php',
    'SProviderAccountType'            => $sqlLayerPath . 'settings/SProviderAccountType.php',
    'GuiEditProviderAccountType'      => $guiPath . 'settings/ProviderAccountTypeEdit.php',
    'ProviderAccountTypeValidator'    => $guiPath . 'settings/ProviderAccountTypeValidator.php',
    'GridSettingsProviderAccountType' => $guiPath . 'settings/ProviderAccountTypeList.php',
    'GuiListProviderAccountType'      => $guiPath . 'settings/ProviderAccountTypeList.php',
    
    'BTicket'                         => $businessPath . 'BTicket.php',
    'OTicket'                         => $sqlLayerPath . 'settings/OTicket.php',
    'STicket'                         => $sqlLayerPath . 'settings/STicket.php',
    'GuiEditTicket'                   => $guiPath . 'settings/TicketEdit.php',
    'TicketValidator'                 => $guiPath . 'settings/TicketValidator.php',
    'GridSettingsTicket'              => $guiPath . 'settings/TicketList.php',
    'GuiListTicket'                   => $guiPath . 'settings/TicketList.php',
    
    'BVoucher'                        => $businessPath . 'BVoucher.php',
    'OVoucher'                        => $sqlLayerPath . 'settings/OVoucher.php',
    'SVoucher'                        => $sqlLayerPath . 'settings/SVoucher.php',
    'GuiEditVoucher'                  => $guiPath . 'settings/VoucherEdit.php',
    'VoucherValidator'                => $guiPath . 'settings/VoucherValidator.php',
    'GridSettingsVoucher'             => $guiPath . 'settings/VoucherList.php',
    'GuiListVoucher'                  => $guiPath . 'settings/VoucherList.php',
    
    'BReservationCondition'           => $businessPath . 'BReservationCondition.php',
    'OReservationCondition'           => $sqlLayerPath . 'settings/OReservationCondition.php',
    'SReservationCondition'           => $sqlLayerPath . 'settings/SReservationCondition.php',
    'OReservationConditionItem'       => $sqlLayerPath . 'settings/OReservationConditionItem.php',
    'SReservationConditionItem'       => $sqlLayerPath . 'settings/SReservationConditionItem.php',
    'GuiEditReservationCondition'     => $guiPath . 'settings/ReservationConditionEdit.php',
    'ReservationConditionValidator'   => $guiPath . 'settings/ReservationConditionValidator.php',
    'GridSettingsReservationCondition'=> $guiPath . 'settings/ReservationConditionList.php',
    'GuiListReservationCondition'     => $guiPath . 'settings/ReservationConditionList.php',
    
    'BNotificationTemplate'           => $businessPath . 'BNotificationTemplate.php',
    'ONotificationTemplate'           => $sqlLayerPath . 'settings/ONotificationTemplate.php',
    'SNotificationTemplate'           => $sqlLayerPath . 'settings/SNotificationTemplate.php',
    'ONotificationTemplateItem'       => $sqlLayerPath . 'settings/ONotificationTemplateItem.php',
    'SNotificationTemplateItem'       => $sqlLayerPath . 'settings/SNotificationTemplateItem.php',
    'GuiEditNotificationTemplate'     => $guiPath . 'settings/NotificationTemplateEdit.php',
    'NotificationTemplateValidator'   => $guiPath . 'settings/NotificationTemplateValidator.php',
    'GridSettingsNotificationTemplate'=> $guiPath . 'settings/NotificationTemplateList.php',
    'GuiListNotificationTemplate'     => $guiPath . 'settings/NotificationTemplateList.php',

    'BDocumentTemplate'               => $businessPath . 'BDocumentTemplate.php',
    'ODocumentTemplate'               => $sqlLayerPath . 'settings/ODocumentTemplate.php',
    'SDocumentTemplate'               => $sqlLayerPath . 'settings/SDocumentTemplate.php',
    'ODocumentTemplateItem'           => $sqlLayerPath . 'settings/ODocumentTemplateItem.php',
    'SDocumentTemplateItem'           => $sqlLayerPath . 'settings/SDocumentTemplateItem.php',
    'GuiEditDocumentTemplate'         => $guiPath . 'settings/DocumentTemplateEdit.php',
    'DocumentTemplateValidator'       => $guiPath . 'settings/DocumentTemplateValidator.php',
    'GridSettingsDocumentTemplate'    => $guiPath . 'settings/DocumentTemplateList.php',
    'GuiListDocumentTemplate'         => $guiPath . 'settings/DocumentTemplateList.php',

    'ReportValidator'                 => $guiPath . 'report/ReportValidator.php',
    'GuiReport'                       => $guiPath . 'report/Report.php',
    'GuiReportMenu'                   => $guiPath . 'report/Menu.php',
    'GuiUserReport'                   => $guiPath . 'report/Customer.php',
    'UserReportValidator'             => $guiPath . 'report/CustomerValidator.php',
    'GuiCreditReport'                 => $guiPath . 'report/Credit.php',
    'CreditReportValidator'           => $guiPath . 'report/CreditValidator.php',
    'GuiReservationReport'            => $guiPath . 'report/Reservation.php',
    'ReservationReportValidator'      => $guiPath . 'report/ReservationValidator.php',
    'GuiAttendeeReport'               => $guiPath . 'report/Attendee.php',
    'AttendeeReportValidator'         => $guiPath . 'report/AttendeeValidator.php',
    'ModuleReportSearch'              => $modulesPath . 'report/eReportSearch.php',
    
    /* Login/Logout */
    'BUser'                           => $businessPath . 'BUser.php',
    'OUser'                           => $sqlLayerPath . 'user/OUser.php',
    'SUser'                           => $sqlLayerPath . 'user/SUser.php',
    'OUserPermanentLogin'             => $sqlLayerPath . 'user/OUserPermanentLogin.php',
    'SUserPermanentLogin'             => $sqlLayerPath . 'user/SUserPermanentLogin.php',
    'OUserRegistration'               => $sqlLayerPath . 'user/OUserRegistration.php',
    'SUserRegistration'               => $sqlLayerPath . 'user/SUserRegistration.php',
    'OUserValidation'                 => $sqlLayerPath . 'user/OUserValidation.php',
    'SUserValidation'                 => $sqlLayerPath . 'user/SUserValidation.php',
    'OUserAttribute'                  => $sqlLayerPath . 'user/OUserAttribute.php',
    'SUserAttribute'                  => $sqlLayerPath . 'user/SUserAttribute.php',
    'OCreditJournal'                  => $sqlLayerPath . 'user/OCreditJournal.php',
    'SCreditJournal'                  => $sqlLayerPath . 'user/SCreditJournal.php',
    'SOrganiser'                      => $sqlLayerPath . 'user/SOrganiser.php',
    'OUserTicket'                     => $sqlLayerPath . 'user/OUserTicket.php',
    'SUserTicket'                     => $sqlLayerPath . 'user/SUserTicket.php',
    'OUserTicketJournal'              => $sqlLayerPath . 'user/OUserTicketJournal.php',
    'SUserTicketJournal'              => $sqlLayerPath . 'user/SUserTicketJournal.php',
    'OPrepaymentInvoice'              => $sqlLayerPath . 'user/OPrepaymentInvoice.php',
    'SPrepaymentInvoice'              => $sqlLayerPath . 'user/SPrepaymentInvoice.php',

    'BDocument'                       => $businessPath . 'BDocument.php',
    'ODocument'                       => $sqlLayerPath . 'user/ODocument.php',
    'SDocument'                       => $sqlLayerPath . 'user/SDocument.php',
    'GridSettingsDocument'            => $guiPath . 'user/DocumentList.php',
    'GuiListDocument'                 => $guiPath . 'user/DocumentList.php',

    'GuiLogin'                        => $guiPath . 'user/Login.php',
    'LoginValidator'                  => $guiPath . 'user/LoginValidator.php',
    'GuiChangePassword'               => $guiPath . 'user/ChangePassword.php',
    'ChangePasswordValidator'         => $guiPath . 'user/ChangePasswordValidator.php',

    /* Administrace uzivatelu */
    'GuiEditUser'                     => $guiPath . 'user/UserEdit.php',
    'UserValidator'                   => $guiPath . 'user/UserValidator.php',
    'GridSettingsUser'                => $guiPath . 'user/UserList.php',
    'GuiListUser'                     => $guiPath . 'user/UserList.php',
    'GuiUserCredit'                   => $guiPath . 'user/UserCredit.php',
    'UserCreditValidator'             => $guiPath . 'user/UserCreditValidator.php',
    'GridSettingsUserTicket'          => $guiPath . 'user/UserTicketList.php',
    'GuiListUserTicket'               => $guiPath . 'user/UserTicketList.php',
    'GuiUserPrepaymentInvoice'        => $guiPath . 'user/UserPrepaymentInvoice.php',
    
    /* Administrace zakazniku */
    'BGps'                            => $businessPath . 'BGps.php',
    'BAddress'                        => $businessPath . 'BAddress.php',
    'BCustomer'                       => $businessPath . 'BCustomer.php',
    'OCustomer'                       => $sqlLayerPath . 'customer/OCustomer.php',
    'SCustomer'                       => $sqlLayerPath . 'customer/SCustomer.php',
    'OProvider'                       => $sqlLayerPath . 'customer/OProvider.php',
    'SProvider'                       => $sqlLayerPath . 'customer/SProvider.php',
    'OProviderSettings'               => $sqlLayerPath . 'customer/OProviderSettings.php',
    'SProviderSettings'               => $sqlLayerPath . 'customer/SProviderSettings.php',
    'OProviderFile'                   => $sqlLayerPath . 'customer/OProviderFile.php',
    'SProviderFile'                   => $sqlLayerPath . 'customer/SProviderFile.php',
    'OProviderInvoice'                => $sqlLayerPath . 'customer/OProviderInvoice.php',
    'SProviderInvoice'                => $sqlLayerPath . 'customer/SProviderInvoice.php',
    'OProviderTextStorage'            => $sqlLayerPath . 'customer/OProviderTextStorage.php',
    'SProviderTextStorage'            => $sqlLayerPath . 'customer/SProviderTextStorage.php',
    'OCenter'                         => $sqlLayerPath . 'customer/OCenter.php',
    'SCenter'                         => $sqlLayerPath . 'customer/SCenter.php',
    'OAddress'                        => $sqlLayerPath . 'customer/OAddress.php',
    'SAddress'                        => $sqlLayerPath . 'customer/SAddress.php',
    'OCustomerRegistration'           => $sqlLayerPath . 'customer/OCustomerRegistration.php',
    'SCustomerRegistration'           => $sqlLayerPath . 'customer/SCustomerRegistration.php',
    'OEmployee'                       => $sqlLayerPath . 'customer/OEmployee.php',
    'SEmployee'                       => $sqlLayerPath . 'customer/SEmployee.php',
    'OAttribute'                      => $sqlLayerPath . 'customer/OAttribute.php',
    'SAttribute'                      => $sqlLayerPath . 'customer/SAttribute.php',
    'OAttributeName'                  => $sqlLayerPath . 'customer/OAttributeName.php',
    'SAttributeName'                  => $sqlLayerPath . 'customer/SAttributeName.php',
    'SProviderPaymentGateway'         => $sqlLayerPath . 'customer/SProviderPaymentGateway.php',
    
    'GuiEditCustomer'                 => $guiPath . 'customer/CustomerEdit.php',
    'CustomerValidator'               => $guiPath . 'customer/CustomerValidator.php',
    'GridSettingsCustomer'            => $guiPath . 'customer/CustomerList.php',
    'GuiListCustomer'                 => $guiPath . 'customer/CustomerList.php',
    'GridSettingsCenter'              => $guiPath . 'customer/ProviderList.php',
    'GridSettingsProvider'            => $guiPath . 'customer/ProviderList.php',
    'GuiListProvider'                 => $guiPath . 'customer/ProviderList.php',
    'GridSettingsProviderInvoice'     => $guiPath . 'customer/ProviderInvoiceList.php',
    'GuiListProviderInvoice'          => $guiPath . 'customer/ProviderInvoiceList.php',
    'GridSettingsProviderTextStorage' => $guiPath . 'customer/ProviderTextStorageList.php',
    'GuiListProviderTextStorage'      => $guiPath . 'customer/ProviderTextStorageList.php',
    'GuiCustomerCredit'               => $guiPath . 'customer/CustomerCredit.php',
    'GuiCustomerInvoice'              => $guiPath . 'customer/CustomerInvoice.php',
    
    /* Administrace akci */
    'BEvent'                          => $businessPath . 'BEvent.php',
    'OEvent'                          => $sqlLayerPath . 'commodity/OEvent.php',
    'SEvent'                          => $sqlLayerPath . 'commodity/SEvent.php',
    'OEventAttendee'                  => $sqlLayerPath . 'commodity/OEventAttendee.php',
    'SEventAttendee'                  => $sqlLayerPath . 'commodity/SEventAttendee.php',
    'OEventAttendeePerson'            => $sqlLayerPath . 'commodity/OEventAttendeePerson.php',
    'SEventAttendeePerson'            => $sqlLayerPath . 'commodity/SEventAttendeePerson.php',
    'OEventAttendeeAttribute'         => $sqlLayerPath . 'commodity/OEventAttendeeAttribute.php',
    'SEventAttendeeAttribute'         => $sqlLayerPath . 'commodity/SEventAttendeeAttribute.php',
    'OEventTag'                       => $sqlLayerPath . 'commodity/OEventTag.php',
    'SEventTag'                       => $sqlLayerPath . 'commodity/SEventTag.php',
    'OEventPortal'                    => $sqlLayerPath . 'commodity/OEventPortal.php',
    'OEventResource'                  => $sqlLayerPath . 'commodity/OEventResource.php',
    'SEventResource'                  => $sqlLayerPath . 'commodity/SEventResource.php',
    'OEventAttribute'                 => $sqlLayerPath . 'commodity/OEventAttribute.php',
    'SEventAttribute'                 => $sqlLayerPath . 'commodity/SEventAttribute.php',
    
    'GuiEditEvent'                    => $guiPath . 'commodity/EventEdit.php',
    'EventValidator'                  => $guiPath . 'commodity/EventValidator.php',
    'GuiEditEventGroup'               => $guiPath . 'commodity/EventGroupEdit.php',
    'EventGroupValidator'             => $guiPath . 'commodity/EventGroupValidator.php',
    'GridSettingsEvent'               => $guiPath . 'commodity/EventList.php',
    'GuiListEvent'                    => $guiPath . 'commodity/EventList.php',
    'GuiGridCellEventDesc'            => $guiPath . 'commodity/EventList.php',
    'GuiGridCellTerm'                 => $guiPath . 'commodity/EventList.php',
    'GuiGridCellCycleTerm'            => $guiPath . 'commodity/EventCycleList.php',
    'GridSettingsEventCycle'          => $guiPath . 'commodity/EventCycleList.php',
    'GuiListEventCycle'               => $guiPath . 'commodity/EventCycleList.php',
    'GuiGridCellEventAttendeePerson'  => $guiPath . 'commodity/EventSubstituteList.php',
    'GridSettingsEventAttendee'       => $guiPath . 'commodity/EventSubstituteList.php',
    'GuiListEventSubstitute'          => $guiPath . 'commodity/EventSubstituteList.php',
    'GuiEditEventSubstitute'          => $guiPath . 'commodity/EventSubstituteEdit.php',
    'EventSubstituteValidator'        => $guiPath . 'commodity/EventSubstituteValidator.php',
    'GuiEventCalendar'                => $guiPath . 'commodity/EventCalendar.php',
    'GuiEventSummary'                 => $guiPath . 'commodity/EventSummary.php',
    'GuiBadge'                        => $guiPath . 'commodity/Badge.php',
    
    /* Administrace zdroju */
    'BResource'                       => $businessPath . 'BResource.php',
    'OResource'                       => $sqlLayerPath . 'commodity/OResource.php',
    'SResource'                       => $sqlLayerPath . 'commodity/SResource.php',
    'OResourceTag'                    => $sqlLayerPath . 'commodity/OResourceTag.php',
    'SResourceTag'                    => $sqlLayerPath . 'commodity/SResourceTag.php',
    'OResourcePortal'                 => $sqlLayerPath . 'commodity/OResourcePortal.php',
    'OResourceAvailability'           => $sqlLayerPath . 'commodity/OResourceAvailability.php',
    'SResourceAvailability'           => $sqlLayerPath . 'commodity/SResourceAvailability.php',
    'OResourceAttribute'              => $sqlLayerPath . 'commodity/OResourceAttribute.php',
    'SResourceAttribute'              => $sqlLayerPath . 'commodity/SResourceAttribute.php',
    
    'GuiEditResource'                 => $guiPath . 'commodity/ResourceEdit.php',
    'ResourceValidator'               => $guiPath . 'commodity/ResourceValidator.php',
    'GridSettingsResource'            => $guiPath . 'commodity/ResourceList.php',
    'GuiListResource'                 => $guiPath . 'commodity/ResourceList.php',
    'GuiResourceCalendar'             => $guiPath . 'commodity/ResourceCalendar.php',
    
    'BResourcePool'                   => $businessPath . 'BResourcePool.php',
    'OResourcePool'                   => $sqlLayerPath . 'commodity/OResourcePool.php',
    'SResourcePool'                   => $sqlLayerPath . 'commodity/SResourcePool.php',
    'OResourcePoolItem'               => $sqlLayerPath . 'commodity/OResourcePoolItem.php',
    'SResourcePoolItem'               => $sqlLayerPath . 'commodity/SResourcePoolItem.php',
    'OResourcePoolTag'                => $sqlLayerPath . 'commodity/OResourcePoolTag.php',
    'SResourcePoolTag'                => $sqlLayerPath . 'commodity/SResourcePoolTag.php',
    'GuiEditResourcePool'             => $guiPath . 'commodity/ResourcePoolEdit.php',
    'ResourcePoolValidator'           => $guiPath . 'commodity/ResourcePoolValidator.php',
    'GridSettingsResourcePool'        => $guiPath . 'commodity/ResourcePoolList.php',
    'GuiListResourcePool'             => $guiPath . 'commodity/ResourcePoolList.php',
    
    'GuiCalendar'                     => $guiPath . 'commodity/Calendar.php',
    
    /* Administrace rezervaci */
    'BReservation'                    => $businessPath . 'BReservation.php',
    'OReservation'                    => $sqlLayerPath . 'reservation/OReservation.php',
    'SReservation'                    => $sqlLayerPath . 'reservation/SReservation.php',
    'OReservationJournal'             => $sqlLayerPath . 'reservation/OReservationJournal.php',
    'SReservationJournal'             => $sqlLayerPath . 'reservation/SReservationJournal.php',
    'OReservationAttribute'           => $sqlLayerPath . 'reservation/OReservationAttribute.php',
    'SReservationAttribute'           => $sqlLayerPath . 'reservation/SReservationAttribute.php',
    'OCreditnote'                     => $sqlLayerPath . 'reservation/OCreditnote.php',
    'SCreditnote'                     => $sqlLayerPath . 'reservation/SCreditnote.php',

    'GuiEditReservation'              => $guiPath . 'reservation/ReservationEdit.php',
    'ReservationValidator'            => $guiPath . 'reservation/ReservationValidator.php',
    'GridSettingsReservation'         => $guiPath . 'reservation/ReservationList.php',
    'GuiListReservation'              => $guiPath . 'reservation/ReservationList.php',
    'GuiReservationTicket'            => $guiPath . 'reservation/ReservationTicket.php',
    'GuiReservationTicketForm'        => $guiPath . 'reservation/ReservationTicketForm.php',
    'GuiReservationReceipt'           => $guiPath . 'reservation/ReservationReceipt.php',
    'GuiReservationInvoice'           => $guiPath . 'reservation/ReservationInvoice.php',
    'GuiReservationCreditnote'        => $guiPath . 'reservation/ReservationCreditnote.php',
    
    /* Providersky web */
    'BPageTemplate'                            => $businessPath . 'BPageTemplate.php',
    'OPageTemplate'                            => $sqlLayerPath . 'providerportal/OPageTemplate.php',
    'SPageTemplate'                            => $sqlLayerPath . 'providerportal/SPageTemplate.php',
    'GuiEditPageTemplate'                      => $guiPath . 'providerportal/PageTemplateEdit.php',
    'PageTemplateValidator'                    => $guiPath . 'providerportal/PageTemplateValidator.php',
    'GridSettingsPageTemplate'                 => $guiPath . 'providerportal/PageTemplateList.php',
    'GuiListPageTemplate'                      => $guiPath . 'providerportal/PageTemplateList.php',
    
    'BPortalTemplate'                          => $businessPath . 'BPortalTemplate.php',
    'OPortalTemplate'                          => $sqlLayerPath . 'providerportal/OPortalTemplate.php',
    'SPortalTemplate'                          => $sqlLayerPath . 'providerportal/SPortalTemplate.php',
    'OPortalTemplatePageTemplate'              => $sqlLayerPath . 'providerportal/OPortalTemplatePageTemplate.php',
    'SPortalTemplatePageTemplate'              => $sqlLayerPath . 'providerportal/SPortalTemplatePageTemplate.php',
    'GuiEditPortalTemplate'                    => $guiPath . 'providerportal/PortalTemplateEdit.php',
    'PortalTemplateValidator'                  => $guiPath . 'providerportal/PortalTemplateValidator.php',
    'GridSettingsPortalTemplate'               => $guiPath . 'providerportal/PortalTemplateList.php',
    'GuiListPortalTemplate'                    => $guiPath . 'providerportal/PortalTemplateList.php',
    
    'BProviderPortal'                          => $businessPath . 'BProviderPortal.php',
    'OProviderPortal'                          => $sqlLayerPath . 'providerportal/OProviderPortal.php',
    'SProviderPortal'                          => $sqlLayerPath . 'providerportal/SProviderPortal.php',
    'OProviderPortalPage'                      => $sqlLayerPath . 'providerportal/OProviderPortalPage.php',
    'SProviderPortalPage'                      => $sqlLayerPath . 'providerportal/SProviderPortalPage.php',
    'OProviderPortalMenu'                      => $sqlLayerPath . 'providerportal/OProviderPortalMenu.php',
    'SProviderPortalMenu'                      => $sqlLayerPath . 'providerportal/SProviderPortalMenu.php',
    'OProviderPortalFile'                      => $sqlLayerPath . 'providerportal/OProviderPortalFile.php',
    'SProviderPortalFile'                      => $sqlLayerPath . 'providerportal/SProviderPortalFile.php',
    'GuiCreateProviderPortal'                  => $guiPath . 'providerportal/ProviderPortalCreate.php',
    'GuiEditProviderPortal'                    => $guiPath . 'providerportal/ProviderPortalEdit.php',
    'ProviderPortalValidator'                  => $guiPath . 'providerportal/ProviderPortalValidator.php',
    'GridSettingsProviderPortal'               => $guiPath . 'providerportal/ProviderPortalList.php',
    'GuiListProviderPortal'                    => $guiPath . 'providerportal/ProviderPortalList.php',
    'GridSettingsProviderPortalPage'           => $guiPath . 'providerportal/ProviderPortalPageList.php',
    'GuiListProviderPortalPage'                => $guiPath . 'providerportal/ProviderPortalPageList.php',
    'GuiEditProviderPortalPage'                => $guiPath . 'providerportal/ProviderPortalPageEdit.php',
    'GuiCreateProviderPortalPage'              => $guiPath . 'providerportal/ProviderPortalPageCreate.php',
    
    'BNotification'                   => $businessPath . 'BNotification.php',
    'ONotification'                   => $sqlLayerPath . 'settings/ONotification.php',
    'SNotification'                   => $sqlLayerPath . 'settings/SNotification.php',
    'ONotificationFile'               => $sqlLayerPath . 'settings/ONotificationFile.php',
    'SNotificationFile'               => $sqlLayerPath . 'settings/SNotificationFile.php',
    );

?>
