insert into state (code,name,disabled) values ('AF','Afghanistan','N');
insert into state (code,name,disabled) values ('AL','Albania','N');
insert into state (code,name,disabled) values ('DZ','Algeria','N');
insert into state (code,name,disabled) values ('AS','American Samoa','N');
insert into state (code,name,disabled) values ('AD','Andorra','N');
insert into state (code,name,disabled) values ('AO','Angola','N');
insert into state (code,name,disabled) values ('AI','Anguilla','N');
insert into state (code,name,disabled) values ('AQ','Antarctica','N');
insert into state (code,name,disabled) values ('AG','Antigua And Barbuda','N');
insert into state (code,name,disabled) values ('AR','Argentina','N');
insert into state (code,name,disabled) values ('AM','Armenia','N');
insert into state (code,name,disabled) values ('AW','Aruba','N');
insert into state (code,name,disabled) values ('AU','Australia','N');
insert into state (code,name,disabled) values ('AT','Austria','N');
insert into state (code,name,disabled) values ('AZ','Azerbaijan','N');
insert into state (code,name,disabled) values ('BS','Bahamas','N');
insert into state (code,name,disabled) values ('BH','Bahrain','N');
insert into state (code,name,disabled) values ('BD','Bangladesh','N');
insert into state (code,name,disabled) values ('BB','Barbados','N');
insert into state (code,name,disabled) values ('BY','Belarus','N');
insert into state (code,name,disabled) values ('BE','Belgium','N');
insert into state (code,name,disabled) values ('BZ','Belize','N');
insert into state (code,name,disabled) values ('BJ','Benin','N');
insert into state (code,name,disabled) values ('BM','Bermuda','N');
insert into state (code,name,disabled) values ('BT','Bhutan','N');
insert into state (code,name,disabled) values ('BO','Bolivia','N');
insert into state (code,name,disabled) values ('BA','Bosnia And Herzegovina','N');
insert into state (code,name,disabled) values ('BW','Botswana','N');
insert into state (code,name,disabled) values ('BV','Bouvet Island','N');
insert into state (code,name,disabled) values ('BR','Brazil','N');
insert into state (code,name,disabled) values ('IO','British Indian Ocean Territory','N');
insert into state (code,name,disabled) values ('BN','Brunei Darussalam','N');
insert into state (code,name,disabled) values ('BG','Bulgaria','N');
insert into state (code,name,disabled) values ('BF','Burkina Faso','N');
insert into state (code,name,disabled) values ('BI','Burundi','N');
insert into state (code,name,disabled) values ('KH','Cambodia','N');
insert into state (code,name,disabled) values ('CM','Cameroon','N');
insert into state (code,name,disabled) values ('CA','Canada','N');
insert into state (code,name,disabled) values ('CV','Cape Verde','N');
insert into state (code,name,disabled) values ('KY','Cayman Islands','N');
insert into state (code,name,disabled) values ('CF','Central African Republic','N');
insert into state (code,name,disabled) values ('TD','Chad','N');
insert into state (code,name,disabled) values ('CL','Chile','N');
insert into state (code,name,disabled) values ('CN','China','N');
insert into state (code,name,disabled) values ('CX','Christmas Island','N');
insert into state (code,name,disabled) values ('CC','Cocos (keeling) Islands','N');
insert into state (code,name,disabled) values ('CO','Colombia','N');
insert into state (code,name,disabled) values ('KM','Comoros','N');
insert into state (code,name,disabled) values ('CG','Congo','N');
insert into state (code,name,disabled) values ('CD','Congo, The Democratic Republic Of The','N');
insert into state (code,name,disabled) values ('CK','Cook Islands','N');
insert into state (code,name,disabled) values ('CR','Costa Rica','N');
insert into state (code,name,disabled) values ('CI','Cote D\'ivoire','N');
insert into state (code,name,disabled) values ('HR','Croatia','N');
insert into state (code,name,disabled) values ('CU','Cuba','N');
insert into state (code,name,disabled) values ('CY','Cyprus','N');
insert into state (code,name,disabled) values ('CZ','Czech Republic','N');
insert into state (code,name,disabled) values ('DK','Denmark','N');
insert into state (code,name,disabled) values ('DJ','Djibouti','N');
insert into state (code,name,disabled) values ('DM','Dominica','N');
insert into state (code,name,disabled) values ('DO','Dominican Republic','N');
insert into state (code,name,disabled) values ('TP','East Timor','N');
insert into state (code,name,disabled) values ('EC','Ecuador','N');
insert into state (code,name,disabled) values ('EG','Egypt','N');
insert into state (code,name,disabled) values ('SV','El Salvador','N');
insert into state (code,name,disabled) values ('GQ','Equatorial Guinea','N');
insert into state (code,name,disabled) values ('ER','Eritrea','N');
insert into state (code,name,disabled) values ('EE','Estonia','N');
insert into state (code,name,disabled) values ('ET','Ethiopia','N');
insert into state (code,name,disabled) values ('FK','Falkland Islands (malvinas)','N');
insert into state (code,name,disabled) values ('FO','Faroe Islands','N');
insert into state (code,name,disabled) values ('FJ','Fiji','N');
insert into state (code,name,disabled) values ('FI','Finland','N');
insert into state (code,name,disabled) values ('FR','France','N');
insert into state (code,name,disabled) values ('GF','French Guiana','N');
insert into state (code,name,disabled) values ('PF','French Polynesia','N');
insert into state (code,name,disabled) values ('TF','French Southern Territories','N');
insert into state (code,name,disabled) values ('GA','Gabon','N');
insert into state (code,name,disabled) values ('GM','Gambia','N');
insert into state (code,name,disabled) values ('GE','Georgia','N');
insert into state (code,name,disabled) values ('DE','Germany','N');
insert into state (code,name,disabled) values ('GH','Ghana','N');
insert into state (code,name,disabled) values ('GI','Gibraltar','N');
insert into state (code,name,disabled) values ('GR','Greece','N');
insert into state (code,name,disabled) values ('GL','Greenland','N');
insert into state (code,name,disabled) values ('GD','Grenada','N');
insert into state (code,name,disabled) values ('GP','Guadeloupe','N');
insert into state (code,name,disabled) values ('GU','Guam','N');
insert into state (code,name,disabled) values ('GT','Guatemala','N');
insert into state (code,name,disabled) values ('GN','Guinea','N');
insert into state (code,name,disabled) values ('GW','Guinea-bissau','N');
insert into state (code,name,disabled) values ('GY','Guyana','N');
insert into state (code,name,disabled) values ('HT','Haiti','N');
insert into state (code,name,disabled) values ('HM','Heard Island And Mcdonald Islands','N');
insert into state (code,name,disabled) values ('VA','Holy See (vatican City State)','N');
insert into state (code,name,disabled) values ('HN','Honduras','N');
insert into state (code,name,disabled) values ('HK','Hong Kong','N');
insert into state (code,name,disabled) values ('HU','Hungary','N');
insert into state (code,name,disabled) values ('IS','Iceland','N');
insert into state (code,name,disabled) values ('IN','India','N');
insert into state (code,name,disabled) values ('ID','Indonesia','N');
insert into state (code,name,disabled) values ('IR','Iran, Islamic Republic Of','N');
insert into state (code,name,disabled) values ('IQ','Iraq','N');
insert into state (code,name,disabled) values ('IE','Ireland','N');
insert into state (code,name,disabled) values ('IL','Israel','N');
insert into state (code,name,disabled) values ('IT','Italy','N');
insert into state (code,name,disabled) values ('JM','Jamaica','N');
insert into state (code,name,disabled) values ('JP','Japan','N');
insert into state (code,name,disabled) values ('JO','Jordan','N');
insert into state (code,name,disabled) values ('KZ','Kazakstan','N');
insert into state (code,name,disabled) values ('KE','Kenya','N');
insert into state (code,name,disabled) values ('KI','Kiribati','N');
insert into state (code,name,disabled) values ('KP','Korea, Democratic People\'s Republic Of','N');
insert into state (code,name,disabled) values ('KR','Korea, Republic Of','N');
insert into state (code,name,disabled) values ('KV','Kosovo','N');
insert into state (code,name,disabled) values ('KW','Kuwait','N');
insert into state (code,name,disabled) values ('KG','Kyrgyzstan','N');
insert into state (code,name,disabled) values ('LA','Lao People\'s Democratic Republic','N');
insert into state (code,name,disabled) values ('LV','Latvia','N');
insert into state (code,name,disabled) values ('LB','Lebanon','N');
insert into state (code,name,disabled) values ('LS','Lesotho','N');
insert into state (code,name,disabled) values ('LR','Liberia','N');
insert into state (code,name,disabled) values ('LY','Libyan Arab Jamahiriya','N');
insert into state (code,name,disabled) values ('LI','Liechtenstein','N');
insert into state (code,name,disabled) values ('LT','Lithuania','N');
insert into state (code,name,disabled) values ('LU','Luxembourg','N');
insert into state (code,name,disabled) values ('MO','Macau','N');
insert into state (code,name,disabled) values ('MK','Macedonia, The Former Yugoslav Republic Of','N');
insert into state (code,name,disabled) values ('MG','Madagascar','N');
insert into state (code,name,disabled) values ('MW','Malawi','N');
insert into state (code,name,disabled) values ('MY','Malaysia','N');
insert into state (code,name,disabled) values ('MV','Maldives','N');
insert into state (code,name,disabled) values ('ML','Mali','N');
insert into state (code,name,disabled) values ('MT','Malta','N');
insert into state (code,name,disabled) values ('MH','Marshall Islands','N');
insert into state (code,name,disabled) values ('MQ','Martinique','N');
insert into state (code,name,disabled) values ('MR','Mauritania','N');
insert into state (code,name,disabled) values ('MU','Mauritius','N');
insert into state (code,name,disabled) values ('YT','Mayotte','N');
insert into state (code,name,disabled) values ('MX','Mexico','N');
insert into state (code,name,disabled) values ('FM','Micronesia, Federated States Of','N');
insert into state (code,name,disabled) values ('MD','Moldova, Republic Of','N');
insert into state (code,name,disabled) values ('MC','Monaco','N');
insert into state (code,name,disabled) values ('MN','Mongolia','N');
insert into state (code,name,disabled) values ('MS','Montserrat','N');
insert into state (code,name,disabled) values ('ME','Montenegro','N');
insert into state (code,name,disabled) values ('MA','Morocco','N');
insert into state (code,name,disabled) values ('MZ','Mozambique','N');
insert into state (code,name,disabled) values ('MM','Myanmar','N');
insert into state (code,name,disabled) values ('NA','Namibia','N');
insert into state (code,name,disabled) values ('NR','Nauru','N');
insert into state (code,name,disabled) values ('NP','Nepal','N');
insert into state (code,name,disabled) values ('NL','Netherlands','N');
insert into state (code,name,disabled) values ('AN','Netherlands Antilles','N');
insert into state (code,name,disabled) values ('NC','New Caledonia','N');
insert into state (code,name,disabled) values ('NZ','New Zealand','N');
insert into state (code,name,disabled) values ('NI','Nicaragua','N');
insert into state (code,name,disabled) values ('NE','Niger','N');
insert into state (code,name,disabled) values ('NG','Nigeria','N');
insert into state (code,name,disabled) values ('NU','Niue','N');
insert into state (code,name,disabled) values ('NF','Norfolk Island','N');
insert into state (code,name,disabled) values ('MP','Northern Mariana Islands','N');
insert into state (code,name,disabled) values ('NO','Norway','N');
insert into state (code,name,disabled) values ('OM','Oman','N');
insert into state (code,name,disabled) values ('PK','Pakistan','N');
insert into state (code,name,disabled) values ('PW','Palau','N');
insert into state (code,name,disabled) values ('PS','Palestinian Territory, Occupied','N');
insert into state (code,name,disabled) values ('PA','Panama','N');
insert into state (code,name,disabled) values ('PG','Papua New Guinea','N');
insert into state (code,name,disabled) values ('PY','Paraguay','N');
insert into state (code,name,disabled) values ('PE','Peru','N');
insert into state (code,name,disabled) values ('PH','Philippines','N');
insert into state (code,name,disabled) values ('PN','Pitcairn','N');
insert into state (code,name,disabled) values ('PL','Poland','N');
insert into state (code,name,disabled) values ('PT','Portugal','N');
insert into state (code,name,disabled) values ('PR','Puerto Rico','N');
insert into state (code,name,disabled) values ('QA','Qatar','N');
insert into state (code,name,disabled) values ('RE','Reunion','N');
insert into state (code,name,disabled) values ('RO','Romania','N');
insert into state (code,name,disabled) values ('RU','Russian Federation','N');
insert into state (code,name,disabled) values ('RW','Rwanda','N');
insert into state (code,name,disabled) values ('SH','Saint Helena','N');
insert into state (code,name,disabled) values ('KN','Saint Kitts And Nevis','N');
insert into state (code,name,disabled) values ('LC','Saint Lucia','N');
insert into state (code,name,disabled) values ('PM','Saint Pierre And Miquelon','N');
insert into state (code,name,disabled) values ('VC','Saint Vincent And The Grenadines','N');
insert into state (code,name,disabled) values ('WS','Samoa','N');
insert into state (code,name,disabled) values ('SM','San Marino','N');
insert into state (code,name,disabled) values ('ST','Sao Tome And Principe','N');
insert into state (code,name,disabled) values ('SA','Saudi Arabia','N');
insert into state (code,name,disabled) values ('SN','Senegal','N');
insert into state (code,name,disabled) values ('RS','Serbia','N');
insert into state (code,name,disabled) values ('SC','Seychelles','N');
insert into state (code,name,disabled) values ('SL','Sierra Leone','N');
insert into state (code,name,disabled) values ('SG','Singapore','N');
insert into state (code,name,disabled) values ('SK','Slovakia','N');
insert into state (code,name,disabled) values ('SI','Slovenia','N');
insert into state (code,name,disabled) values ('SB','Solomon Islands','N');
insert into state (code,name,disabled) values ('SO','Somalia','N');
insert into state (code,name,disabled) values ('ZA','South Africa','N');
insert into state (code,name,disabled) values ('GS','South Georgia And The South Sandwich Islands','N');
insert into state (code,name,disabled) values ('ES','Spain','N');
insert into state (code,name,disabled) values ('LK','Sri Lanka','N');
insert into state (code,name,disabled) values ('SD','Sudan','N');
insert into state (code,name,disabled) values ('SR','Suriname','N');
insert into state (code,name,disabled) values ('SJ','Svalbard And Jan Mayen','N');
insert into state (code,name,disabled) values ('SZ','Swaziland','N');
insert into state (code,name,disabled) values ('SE','Sweden','N');
insert into state (code,name,disabled) values ('CH','Switzerland','N');
insert into state (code,name,disabled) values ('SY','Syrian Arab Republic','N');
insert into state (code,name,disabled) values ('TW','Taiwan, Province Of China','N');
insert into state (code,name,disabled) values ('TJ','Tajikistan','N');
insert into state (code,name,disabled) values ('TZ','Tanzania, United Republic Of','N');
insert into state (code,name,disabled) values ('TH','Thailand','N');
insert into state (code,name,disabled) values ('TG','Togo','N');
insert into state (code,name,disabled) values ('TK','Tokelau','N');
insert into state (code,name,disabled) values ('TO','Tonga','N');
insert into state (code,name,disabled) values ('TT','Trinidad And Tobago','N');
insert into state (code,name,disabled) values ('TN','Tunisia','N');
insert into state (code,name,disabled) values ('TR','Turkey','N');
insert into state (code,name,disabled) values ('TM','Turkmenistan','N');
insert into state (code,name,disabled) values ('TC','Turks And Caicos Islands','N');
insert into state (code,name,disabled) values ('TV','Tuvalu','N');
insert into state (code,name,disabled) values ('UG','Uganda','N');
insert into state (code,name,disabled) values ('UA','Ukraine','N');
insert into state (code,name,disabled) values ('AE','United Arab Emirates','N');
insert into state (code,name,disabled) values ('GB','United Kingdom','N');
insert into state (code,name,disabled) values ('US','United States','N');
insert into state (code,name,disabled) values ('UM','United States Minor Outlying Islands','N');
insert into state (code,name,disabled) values ('UY','Uruguay','N');
insert into state (code,name,disabled) values ('UZ','Uzbekistan','N');
insert into state (code,name,disabled) values ('VU','Vanuatu','N');
insert into state (code,name,disabled) values ('VE','Venezuela','N');
insert into state (code,name,disabled) values ('VN','Viet Nam','N');
insert into state (code,name,disabled) values ('VG','Virgin Islands, British','N');
insert into state (code,name,disabled) values ('VI','Virgin Islands, U.s.','N');
insert into state (code,name,disabled) values ('WF','Wallis And Futuna','N');
insert into state (code,name,disabled) values ('EH','Western Sahara','N');
insert into state (code,name,disabled) values ('YE','Yemen','N');
insert into state (code,name,disabled) values ('ZM','Zambia','N');
insert into state (code,name,disabled) values ('ZW','Zimbabwe','N');
